stages:
  feature_engineering:
    cmd: cd 01_feature_engineering && uv run python feature_engineering.py
    deps:
      - 01_feature_engineering/feature_engineering.py
      - data/results.csv
    params:
      - params.yaml:
          - feature_engineering

  preprocessing:
    cmd: cd 02_preprocessing && uv run python preprocessing.py
    deps:
      - 02_preprocessing/preprocessing.py
      - data/df_featured.csv
    params:
      - params.yaml:
          - preprocessing

  train:
    cmd: cd 03_train_model_kubernetes && DATA_DIR=$(pwd)/../data MODEL_DIR=$(pwd)/../data MODEL_TYPE=xgboost uv run python train.py
    deps:
      - 03_train_model_kubernetes/train.py
      - data/X_train.csv
      - data/y_train.csv
      - data/best_params.json
    params:
      - params.yaml:
          - model

  evaluate:
    cmd: cd 04_evaluate_model && uv run python evaluate_model.py
    deps:
      - 04_evaluate_model/evaluate_model.py
      - data/model.pkl
      - data/X_test.csv
      - data/y_test.csv

  monitoring:
    cmd: cd 09_model_monitoring && uv run python model_monitoring.py
    deps:
      - 09_model_monitoring/model_monitoring.py
      - data/model.pkl
      - data/X_train.csv
      - data/X_test.csv
      - data/y_test.csv
